import classes from './Authentificated.module.css';
import { ToastContainer } from 'react-toastify';
import Head from 'next/head';
import MenuHeader from '../../components/MenuHeader/MenuHeader';
import { ReactNode } from 'react';

interface props {
  readonly children: ReactNode;
  readonly title?: string;
}

export default function AuthentificatedLayout({ children, title }: props) {
  return (
    <div className={classes.container}>
      <Head>
        <title>{title && `${title} |`}Njörd - ARRD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={classes.header}>
        <MenuHeader />
      </header>
      <main className={classes.main}>{children}</main>
      <ToastContainer
        position="bottom-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="dark"
      />
    </div>
  );
}
